### ISSUE TITLE
Integrations Achemy -> Solidus  | Devise | Base controller

### ISSUE THREAD

**Issue by oniram88** [AlchemyCMS/alchemy-solidus#10]
This won't be an issue...it's more a suggestion to insert as Faq in wiki.
If you use gem 'solidus_auth_devise' and will you login in the frontend interface with alchemy helpers used in the layout, you must make a change in devise configurations and set the correct parent_controller:

    Devise.setup do |config|
        config.parent_controller = "Spree::BaseController"
    end

That because the default parent_controller is ApplicationController and we attach all our alchemy helpers in the Spree::BaseController in the /lib/alchemy/solidus/alchemy_in_solidus.rb file.

**Comment by tvdeyen** [comment]
👍 IMO we should add this to `alchemy_in_solidus.rb` or at least mention it in the README. Would you open a PR? Thanks for reporting

**Comment by oniram88** [comment]
But you say it's better to make a comment in the readme file and let the developer attach this or it's better to add an initilizer in the engine and check if it's the case to set the parent controller...
for me it's better to let the developer take the decision of what it's better for him.

**Comment by tvdeyen** [comment]
Absolutely. The decision the developer makes is which file she includes, right? So, IMO we should add this into the `alchemy_in_solidus.rb` file. 

We want to make the integration as transparent, but in the same time, as easy as possible for developers. Since the Devise base controller is mandatory we should make this automatically happen, if the developer made he decision what kind of integration she wants. Alchemy in Solidus or Solidus in Alchemy. 

WDTY?

**Comment by oniram88** [comment]
Take a look at the PR https://github.com/AlchemyCMS/alchemy-solidus/pull/12

**Comment by tvdeyen** [comment]
Great! Thanks
