### ISSUE TITLE
undefined local variable or method `cart_link_url' 

### ISSUE THREAD

**Issue by harinsa** [AlchemyCMS/alchemy-solidus#2]
`undefined local variable or method `cart_link_url' for #<#<Class:0x007fcd3cc64f38>:0x007fcd3cc40278>`

Seems like alchemy was not able to access the url helpers defined in solidus.

**Comment by tvdeyen** [comment]
Thanks for reporting. Please let me see the trace. I am guessing this is because Solidus does not use their routing proxy object. So instead using `solidus.cart_link_url` they are just using `cart_link_url`. And since we are in Alchemy controller scope, Rails can't resolve the url without knowing the routes of Solidus engine.

**Comment by harinsa** [comment]
https://gist.github.com/harinsa/08f46db8eb8e3d387685

**Comment by harinsa** [comment]
problem disappear when using the master branch of solidus.

**Comment by tvdeyen** [comment]
@harinsa is this still an issue then? Can we close it?

**Comment by harinsa** [comment]
I did not try it any further, so I'm not sure if it's still an issue. You can close it if you cannot reproduce it.
